apiVersion: batch/v1
kind: Job
metadata:
  name: job-example # replace with "${USER_NAME}-{JOB_NAME}"
  namespace: cogrob
spec:
  ttlSecondsAfterFinished: 86400 # Wait one day to delete completed jobs
  template:
    spec:
      containers:
        - name: gpu-container
          image: pytorch/pytorch:1.2-cuda10.0-cudnn7-runtime # docker image
          # imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
          args:
            - "python ${my_script}.py" # replace with actual command
            # For multiple commands, concatenate them with &&
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "2"
              memory: "8Gi"
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: cogrob-avl-west-vol
              mountPath: /avl-west
      volumes:
        - name: cogrob-avl-west-vol
          persistentVolumeClaim:
            claimName: cogrob-avl-west-vol
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-RTX-2080-Ti
  backoffLimit: 0 # The number of attempts to restart after crash
