apiVersion: batch/v1
kind: Job
metadata:
  name: job-example # replace with "${USER_NAME}-{JOB_NAME}"
  namespace: cogrob
spec:
  ttlSecondsAfterFinished: 86400 # Wait one day to delete completed jobs
  template:
    spec:
      containers:
        - name: gpu-container
          image: pytorch/pytorch:1.2-cuda10.0-cudnn7-runtime # docker image
          # imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
          args:
            - "python ${my_script}.py" # replace with actual command
            # For multiple commands, concatenate them with &&
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "2"
              memory: "8Gi"
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: cogrob-avl-west-vol
              mountPath: /avl-west
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: cogrob-avl-west-vol
          persistentVolumeClaim:
            claimName: cogrob-avl-west-vol
      restartPolicy: Never
      # uncomment below if you need to use tainted nodes
      # tolerations:
      #   - key: "nautilus.io/cogrob"
      #     operator: "Equal"
      #     value: "true"
      #     effect: "NoSchedule" 
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                    - NVIDIA-GeForce-RTX-3090
                    - NVIDIA-A10
                    # - NVIDIA-RTX-A5000
                    # - Quadro-RTX-6000
                    # - Tesla-V100-SXM2-32GB
                    # - NVIDIA-A40
                    # - NVIDIA-RTX-A6000
                    # - Quadro-RTX-8000
                    # - NVIDIA-A100-SXM4-80GB
                    # - NVIDIA-A100-PCIE-40GB
                    # - NVIDIA-TITAN-RTX
                  # example to exclude some host in case of error
                  # - key: kubernetes.io/hostname
                  #   operator: NotIn
                  #   values:
                  #     - my.hostname.net
  backoffLimit: 0 # The number of attempts to restart after crash
