apiVersion: v1
kind: Pod
metadata:
  name: pod-example # replace with "${USER_NAME}-{POD_NAME}"
  namespace: cogrob
spec:
  containers:
    - name: gpu-container
      image: pytorch/pytorch:1.2-cuda10.0-cudnn7-runtime # docker image
      # imagePullPolicy: Always
      args: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "1"
          memory: "4Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "2"
          memory: "8Gi"
          nvidia.com/gpu: "1"
      volumeMounts:
        - name: cogrob-avl-west-vol
          mountPath: /avl-west
  volumes:
    - name: cogrob-avl-west-vol
      persistentVolumeClaim:
        claimName: cogrob-avl-west-vol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-2080-Ti
